import tensorflow as tf

tf.app.flags.DEFINE_boolean('log_accuracy', False, '')
tf.app.flags.DEFINE_boolean('log_gradient', False, '')
tf.app.flags.DEFINE_boolean('evaluate_std', False, '')
tf.app.flags.DEFINE_boolean('evaluate_tch', False, '')
tf.app.flags.DEFINE_boolean('log_model_size', False, '')
# dataset
tf.app.flags.DEFINE_integer('channels', 1, '')
tf.app.flags.DEFINE_integer('image_size', 28, '')
tf.app.flags.DEFINE_integer('num_label', 10, '')
tf.app.flags.DEFINE_integer('train_size', 60000, '')
tf.app.flags.DEFINE_integer('valid_size', 0, '')
tf.app.flags.DEFINE_string('dataset_dir', None, '')
tf.app.flags.DEFINE_string('preprocessing_name', None, '')
tf.app.flags.DEFINE_string('gradient_dir', '../gradients', '')
tf.app.flags.DEFINE_string('gradient_file', 'results/wt_gumbel.txt', '')
tf.app.flags.DEFINE_string('eps_file', 'results/wt_gumbel.eps', '')
tf.app.flags.DEFINE_string('acc_file', 'results/wt_gumbel.acc', '')
tf.app.flags.DEFINE_string('tch_file', 'results/intellstd/tch.acc', '')
tf.app.flags.DEFINE_string('size_file', 'results/model_size.txt', '')
# model
tf.app.flags.DEFINE_string('dis_model_name', None, '')
tf.app.flags.DEFINE_string('gen_model_name', None, '')
tf.app.flags.DEFINE_string('tch_model_name', None, '')
tf.app.flags.DEFINE_float('dis_keep_prob', 0.50, '')
tf.app.flags.DEFINE_float('gen_keep_prob', 0.88, '')
tf.app.flags.DEFINE_float('tch_keep_prob', 0.50, '')
tf.app.flags.DEFINE_float('dis_weight_decay', 0.00004, 'l2 coefficient')
tf.app.flags.DEFINE_float('gen_weight_decay', 0.00004, 'l2 coefficient')
tf.app.flags.DEFINE_float('tch_weight_decay', 0.00004, 'l2 coefficient')
tf.app.flags.DEFINE_string('dis_model_ckpt', None, '')
tf.app.flags.DEFINE_string('gen_model_ckpt', None, '')
tf.app.flags.DEFINE_string('tch_model_ckpt', None, '')
tf.app.flags.DEFINE_integer('hidden_size', 800, '')
# optimization
tf.app.flags.DEFINE_integer('num_epoch', 200, '')
tf.app.flags.DEFINE_integer('num_dis_epoch', 20, '')
tf.app.flags.DEFINE_integer('num_gen_epoch', 10, '')
tf.app.flags.DEFINE_integer('num_tch_epoch', 10, '')
tf.app.flags.DEFINE_integer('batch_size', 128, '')
tf.app.flags.DEFINE_string('optimizer', 'adam', 'adam|rmsprop|sgd')
tf.app.flags.DEFINE_float('dis_learning_rate', 1e-3, '')
tf.app.flags.DEFINE_float('gen_learning_rate', 1e-3, '')
tf.app.flags.DEFINE_float('tch_learning_rate', 1e-3, '')
tf.app.flags.DEFINE_integer('num_negative', 10, '')
tf.app.flags.DEFINE_integer('num_positive', 10, '')
# kdgan
tf.app.flags.DEFINE_float('kd_hard_pct', 0.7, '')
tf.app.flags.DEFINE_float('kd_soft_pct', 0.3, '')
tf.app.flags.DEFINE_float('temperature', 3.0, '')
tf.app.flags.DEFINE_float('noisy_ratio', 0.005, '')
tf.app.flags.DEFINE_float('noisy_sigma', 0.005, '')
tf.app.flags.DEFINE_string('kd_model', 'mimic', 'mimic|distn|noisy')
tf.app.flags.DEFINE_float('intelltch_weight', 0.5, '')
tf.app.flags.DEFINE_float('distilled_weight', 1.0, '')
tf.app.flags.DEFINE_float('intellstd_weight', 0.0, '')
tf.app.flags.DEFINE_float('gumbel_temperature', 10., '')
tf.app.flags.DEFINE_float('gumbel_end_temperature', 0.1, '')
tf.app.flags.DEFINE_float('gumbel_temperature_decay_factor', 0.88, '')
tf.app.flags.DEFINE_boolean('enable_gumbel', True, '')

flags = tf.app.flags.FLAGS
